Pqr hexagonal to cuboid
mlund/faunus pull request #328
Opened 2020-09-22 05:42 UTC by mlund

Adds function to convert hexagonal prism to cuboid and apply it in `savestate` for PQR output with the optional keyword `convert_hexagon`.

2020-09-29 23:12 UTC, rc83 requested changes
The algorithm is surprisingly simple, isn’t it? Beside minor comments, I have one big no-no regarding references to a unique pointer. ¶ The more I think about the hexagonal geometry, the more I am persuaded that Faunus should internally work with a rhombic geometry with transformation from and to hexagonal one on input and output, respectively.

2020-10-02 05:59 UTC, mlund commented on src/geometry.cpp
> +std::unique_ptr<GeometryImplementation> &Chameleon::getGeometryImplementation() { return geometry; }
fixed!

2020-10-02 06:09 UTC, mlund commented on src/analysis.cpp
> +                    dynamic_cast<Geometry::HexagonalPrism *>(spc.geo.getGeometryImplementation().get());
fixed

2020-10-02 06:11 UTC, mlund commented on src/analysis.cpp
> +            }
I agree, that's the future and more economic way to go!

2020-10-02 06:17 UTC, mlund commented on src/geometry.cpp
> +                                                         const ParticleVector &particles) {
Yes, a range would be neat but we still need to create and return the Cuboid object.

2020-10-02 06:50 UTC, mlund commented on src/geometry.cpp
> +
fixed!

2020-10-02 10:25 UTC, merged